[supabase]
url = "https://rpahogaibaowavamxyft.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwYWhvZ2FpYmFvd2F2YW14eWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxNDQxNzIsImV4cCI6MjA5MjcyMDE3Mn0.MeOnLqJDw3vI49ftEwLrcnkUPtL1ko8ZmcQYk9prEL0"

[culqi]
public_key = "pk_test_70Q9kFXGx5lmDJBT"
secret_key = "sk_test_s20Sq64LMSHj27kQ"

[google_oauth]
client_id = "727827073430-s6psu8clr4m2a5dks48q0q9vtqgka9sn.apps.googleusercontent.com"
client_secret = "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"

[app]
redirect_url = "http://localhost:8501"
whatsapp_admin_url = "https://w.app/s58dpa"

[payments]
yape_qr_path = "assets/qr_pago.png"
