[supabase]
url = "https://rpahogaibaowavamxyft.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwYWhvZ2FpYmFvd2F2YW14eWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxNDQxNzIsImV4cCI6MjA5MjcyMDE3Mn0.MeOnLqJDw3vI49ftEwLrcnkUPtL1ko8ZmcQYk9prEL0"